baseURL: "/"
languageCode: en-us
title: Transit Map SF
theme: "hugo-tranquilpeak-theme"

menu:
  main:
    - weight: 1
      identifier: about
      name: "About"
      pre: <i class="sidebar-button-icon fas fa-lg fa-info-circle" aria-hidden="true"></i>
      url: "/about/"

author:
  name: "Transit Map SF"
  picture: 'images/icon.png'
  bio: "A map to track transit breakdowns and time estimations. Data is refreshed every 10 minutes"

params:

  description: Hugo tranquilpeak theme demo
  syntaxHighlighter: highlight.js
  clearReading: true
  hierarchicalCategories: true
  sidebarBehavior: 4
  coverImage: 'images/cover_image.png'
  imageGallery: true
  thumbnailImage: true
  thumbnailImagePosition: bottom
  autoThumbnailImage: true
  customJS:
    - src: >-
  favicon: "/images/favicon.png"